version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull loadimpact/k6 image..
      - docker pull loadimpact/k6
  build:
    commands:
      - echo Run performance test
      - docker run -i loadimpact/k6 run - <scripts/cloud-test.js
  post_build:
    commands:
      - echo Performance test complete on https://group4-static.s3.ap-southeast-1.amazonaws.com/index.html
